version: '3.8'

services:

  api:
    container_name: budgetchecker_api
    build:
      context: ../be/budgetchecker_backend
      dockerfile: budgetchecker_backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=budgetdb;user=budget_user;password=budget_pass
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=budget_user
      - RabbitMQ__Password=budget_pass
    depends_on:
      - mysql
      - rabbitmq
    restart: unless-stopped
    networks:
      - budget_network

  mysql:
    image: mysql:8.0
    container_name: budgetchecker_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: budgetdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - budget_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: budgetchecker_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=budget_user
      - RABBITMQ_DEFAULT_PASS=budget_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - budget_network

networks:
  budget_network:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data: